Automatic filling of file types in docs

diff --git a/.github/workflows/python-package.yml b/.github/workflows/python-package.yml
--- a/.github/workflows/python-package.yml
+++ b/.github/workflows/python-package.yml
@@ -58,4 +58,21 @@ jobs:
             echo "Error: Parameters overview not updated, run in docs folder: python parse_tables.py"
             exit 1
           fi
+      - name: check if parse settings TOMLs changed
+        id: toml_changed
+        run: |
+          if git diff --name-only origin/main...HEAD | grep -q 'io_parse_settings.*\.toml'; then
+            echo "changed=true" >> $GITHUB_OUTPUT
+          else
+            echo "changed=false" >> $GITHUB_OUTPUT
+          fi
+      - name: ensure input files documentation tables are up-to-date
+        if: steps.toml_changed.outputs.changed == 'true'
+        run: |
+          cd docs
+          python generate_input_tables.py
+          if git diff -- available-modules/active-modules/*.md | grep .; then
+            echo "Error: Input files tables not updated, run: cd docs && python generate_input_tables.py"
+            exit 1
+          fi
 
